# Time management API

@baseUrl =  http://localhost:8000/api/v1/tasks

### GET the task list
GET {{baseUrl}}

### POST the task list
POST {{baseUrl}}
Content-Type: application/json

{
    "task": "playing",
    "hr":10,
    "type": "something Different"
}

### PUT the task list
PATCH {{baseUrl}}
Content-Type: application/json

{
    "_id": "66e5b7e3a0ba2e8eaf99ea17",
    "hr": 60,
    "type": "bad"
}
### DELETE the task list
DELETE {{baseUrl}}/66e5b7e3a0ba2e8eaf99ea17